// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace Asp_net_web_api_template.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BookingId");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("From")
                        .HasColumnType("datetime2");

                    b.Property<bool>("PaymentReceived")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("To")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9987b490-5b67-41b8-a9d6-9cc45b50481d"),
                            CustomerId = new Guid("2c52045b-b323-424e-bf04-c27dcc2e0a33"),
                            From = new DateTime(2019, 5, 9, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            PaymentReceived = true,
                            Status = 2,
                            To = new DateTime(2019, 6, 9, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            VehicleId = new Guid("acf49e7d-4d0c-4ea0-b3cc-9aee88b88a7a")
                        },
                        new
                        {
                            Id = new Guid("c3e363e2-9550-4d5e-8b33-de3a23f69884"),
                            CustomerId = new Guid("2c52045b-b323-424e-bf04-c27dcc2e0a33"),
                            From = new DateTime(2022, 12, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentReceived = true,
                            Status = 2,
                            To = new DateTime(2022, 12, 2, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleId = new Guid("afb387cd-9ca2-4fe6-aff2-a2163c92cb59")
                        },
                        new
                        {
                            Id = new Guid("bd8512a0-dfc9-4572-b9b6-7e73db3b8c23"),
                            CustomerId = new Guid("20c11b5c-243c-4e41-acff-a2f1072aee2f"),
                            From = new DateTime(2023, 2, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentReceived = false,
                            Status = 1,
                            To = new DateTime(1, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleId = new Guid("3462f9e4-2bda-4d44-af37-5521a76f1419")
                        });
                });

            modelBuilder.Entity("Entities.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CustomerId");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("DateBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2c52045b-b323-424e-bf04-c27dcc2e0a33"),
                            Address = "Campus Universitário - Lagoa Nova, Natal - RN, 59078-970",
                            DateBirth = new DateTime(1990, 12, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Lorem Ipsum é simplesmente uma simulação de texto da indústria tipográfica e de impressos, e vem sendo utilizado desde o século XVI",
                            Email = "fulano@email.com",
                            Gender = 0,
                            Name = "Fulano"
                        },
                        new
                        {
                            Id = new Guid("20c11b5c-243c-4e41-acff-a2f1072aee2f"),
                            Address = "Av. Nevaldo Rocha, 3775 - Tirol, Natal - RN, 59015-450",
                            DateBirth = new DateTime(2000, 4, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Lorem Ipsum é simplesmente uma simulação de texto da indústria tipográfica e de impressos, e vem sendo utilizado desde o século XVI",
                            Email = "cricrana@email.com",
                            Gender = 1,
                            Name = "Cricrana"
                        });
                });

            modelBuilder.Entity("Entities.Models.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("VehicleId");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("Color")
                        .HasColumnType("int");

                    b.Property<double>("DailyRentalFee")
                        .HasColumnType("float");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Mileage")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("acf49e7d-4d0c-4ea0-b3cc-9aee88b88a7a"),
                            Category = 2,
                            Color = 4,
                            DailyRentalFee = 118.34999999999999,
                            Manufacturer = "Fiat",
                            Mileage = 60000,
                            Model = "Fiat Siena"
                        },
                        new
                        {
                            Id = new Guid("afb387cd-9ca2-4fe6-aff2-a2163c92cb59"),
                            Category = 2,
                            Color = 0,
                            DailyRentalFee = 156.0,
                            Manufacturer = "Hyundai",
                            Mileage = 17500,
                            Model = "HB20"
                        },
                        new
                        {
                            Id = new Guid("3462f9e4-2bda-4d44-af37-5521a76f1419"),
                            Category = 3,
                            Color = 3,
                            DailyRentalFee = 256.0,
                            Manufacturer = "Fiat",
                            Mileage = 35000,
                            Model = "Fiat Doblo"
                        });
                });

            modelBuilder.Entity("Entities.Models.Booking", b =>
                {
                    b.HasOne("Entities.Models.Customer", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Vehicle", "Vehicle")
                        .WithMany("Bookings")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Entities.Models.Customer", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("Entities.Models.Vehicle", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
